//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monkey.Processing.UI.Properties
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpatialModelUIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpatialModelUIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeospatialProcessModeling.UI.Properties.SpatialModelUIResource", typeof(SpatialModelUIResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否保存当前模型.
        /// </summary>
        internal static string String_IsSaveCurrentModel {
            get {
                return ResourceManager.GetString("String_IsSaveCurrentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否保存模型&quot;%s&quot;.
        /// </summary>
        internal static string String_IsSaveModel {
            get {
                return ResourceManager.GetString("String_IsSaveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML模型文件(*.xml;)|*.xml;||Python模型文件(*.py;)|*.py;.
        /// </summary>
        internal static string String_Model_Filter {
            get {
                return ResourceManager.GetString("String_Model_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python模型文件(*.py;)|*.py;||.
        /// </summary>
        internal static string String_PythonModel_Filter {
            get {
                return ResourceManager.GetString("String_PythonModel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML模型文件(*.xml;)|*.xml;||.
        /// </summary>
        internal static string String_XMLModel_Filter {
            get {
                return ResourceManager.GetString("String_XMLModel_Filter", resourceCulture);
            }
        }
    }
}
